### ISSUE TITLE
missing images in user setting

### ISSUE THREAD

**Issue by wini2** [3m5/typo3-enhanced-backend#47]
Hi,
thanks for that very nice extension.

My installation is in a subdirectory mydomain.de/devcms/. The images in the user settings dialog lack of the segment-part.
mydomain.de/typo3conf/ext/enhanced_backend/Resources/Public/Icons/Caret-left.svg
instead of
mydomain.de/**devcms**/typo3conf/ext/enhanced_backend/Resources/Public/Icons/Caret-left.svg

![be-user_settings](https://user-images.githubusercontent.com/6897742/225094416-2d5e878d-ad4c-4b37-82cd-378acbb1ad76.png)

This behaviour is only in the user settings. For the other icons etc. in the BE it works, when I alter a setting for my user.

**Comment by 3m5suchandt** [comment]
Fixed in https://github.com/3m5/typo3-enhanced-backend/releases/tag/v0.0.4
